import type {NextPage} from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import * as React from "react";
import {AppLayout} from "@/layouts/AppLayout";

const Home: NextPage = () => {
    return (
        <div>
            <div className={styles.container}>
                <Head>
                    <title>Keto App</title>
                    <meta name="description"
                          content="Generated by create next app"/>
                    <link rel="icon" href="/k_1.ico"/>
                </Head>
                <main >
                    <AppLayout/>
                </main>
            </div>
        </div>

    )
}

export default Home
